name: laps
description: A mobile application for Laps

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  get_it: ^7.1.3
  http: ^0.13.3
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.4
  device_preview: ^0.7.3
  another_flushbar: ^1.10.22
  flutter_html: ^2.1.0
  intl: ^0.17.0
  html_unescape: ^2.0.0
  youtube_player_flutter: ^8.0.0
  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.16.8
  flutter_test:
    sdk: flutter
  faker: ^2.0.0-rc.2
  mockito: ^5.0.7
  build_runner: ^2.0.2

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/user/no-user.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Nexa
      fonts:
         - asset: assets/fonts/Nexa_Light.otf
         - asset: assets/fonts/Nexa_Bold.otf
           weight: 900
    - family: Raleway
      fonts:
         - asset: assets/fonts/Raleway-Regular.ttf
         - asset: assets/fonts/Raleway-Bold.ttf
           weight: 900
         - asset: assets/fonts/Raleway-Italic.ttf
           style: italic
    - family: MyFlutterApp
      fonts:
         - asset: assets/fonts/MyFlutterApp.ttf
    - family: MyFlutterApp2
      fonts:
         - asset: assets/fonts/MyFlutterApp2.ttf
